'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class Inicio

    '''<summary>
    '''Control Content1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents Content1 As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''Control litDashboardTitle.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents litDashboardTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Control litWelcomeMessage.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents litWelcomeMessage As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Control litGestionTickets.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents litGestionTickets As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Control lnkGestionTickets.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lnkGestionTickets As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Control lnkTicketsAbiertos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lnkTicketsAbiertos As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Control litTicketsAbiertos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents litTicketsAbiertos As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Control metricTicketsAbiertos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents metricTicketsAbiertos As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control litTicketsCerrados.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents litTicketsCerrados As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Control metricTicketsCerrados.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents metricTicketsCerrados As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control litTicketsEnProceso.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents litTicketsEnProceso As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Control metricTicketsEnProceso.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents metricTicketsEnProceso As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control litTicketsPendientes.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents litTicketsPendientes As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Control metricTicketsPendientes.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents metricTicketsPendientes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control litTicketsUrgentes.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents litTicketsUrgentes As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Control metricTicketsUrgentes.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents metricTicketsUrgentes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control litTotalTickets.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents litTotalTickets As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Control metricTotalTickets.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents metricTotalTickets As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control litChartTicketsByStatus.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents litChartTicketsByStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Control chartTicketsByStatus.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chartTicketsByStatus As Global.DevExpress.XtraCharts.Web.WebChartControl

    '''<summary>
    '''Control litChartTicketsByMonth.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents litChartTicketsByMonth As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Control chartTicketsByMonth.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chartTicketsByMonth As Global.DevExpress.XtraCharts.Web.WebChartControl

    '''<summary>
    '''Control litRoleInfo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents litRoleInfo As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Control litRoleDescription.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents litRoleDescription As Global.System.Web.UI.WebControls.Literal
End Class
