'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class CategoriasTicket

    Protected WithEvents btnNuevo As Global.DevExpress.Web.ASPxButton
    Protected WithEvents btnRefrescar As Global.DevExpress.Web.ASPxButton
    Protected WithEvents btnExportarExcel As Global.DevExpress.Web.ASPxButton
    Protected WithEvents txtBuscar As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents cboFiltroActivo As Global.DevExpress.Web.ASPxComboBox
    Protected WithEvents gridCategorias As Global.DevExpress.Web.ASPxGridView
    Protected WithEvents popupCategoria As Global.DevExpress.Web.ASPxPopupControl
    Protected WithEvents hfCategoriaId As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents txtNombre As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtDescripcion As Global.DevExpress.Web.ASPxMemo
    Protected WithEvents txtIconoClase As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtColor As Global.DevExpress.Web.ASPxColorEdit
    Protected WithEvents chkActivo As Global.DevExpress.Web.ASPxCheckBox
    Protected WithEvents btnGuardar As Global.DevExpress.Web.ASPxButton
    Protected WithEvents btnCancelar As Global.DevExpress.Web.ASPxButton
    Protected WithEvents popupSLA As Global.DevExpress.Web.ASPxPopupControl
    Protected WithEvents hfCategoriaIdSLA As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents gridSLA As Global.DevExpress.Web.ASPxGridView
    Protected WithEvents btnCerrarSLA As Global.DevExpress.Web.ASPxButton

End Class
