'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class Parcelas
    Protected WithEvents btnNuevo As Global.DevExpress.Web.ASPxButton
    Protected WithEvents btnRefrescar As Global.DevExpress.Web.ASPxButton
    Protected WithEvents btnExportarExcel As Global.DevExpress.Web.ASPxButton
    Protected WithEvents txtBuscar As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents cboFiltroActivo As Global.DevExpress.Web.ASPxComboBox
    Protected WithEvents gridParcelas As Global.DevExpress.Web.ASPxGridView
    Protected WithEvents popupParcela As Global.DevExpress.Web.ASPxPopupControl
    Protected WithEvents hfId As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents txtNombre As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtDescripcion As Global.DevExpress.Web.ASPxMemo
    Protected WithEvents txtSuperficie As Global.DevExpress.Web.ASPxSpinEdit
    Protected WithEvents cboUnidadSuperficie As Global.DevExpress.Web.ASPxComboBox
    Protected WithEvents cboEntidad As Global.DevExpress.Web.ASPxComboBox
    Protected WithEvents txtLatitud As Global.DevExpress.Web.ASPxSpinEdit
    Protected WithEvents txtLongitud As Global.DevExpress.Web.ASPxSpinEdit
    Protected WithEvents chkActivo As Global.DevExpress.Web.ASPxCheckBox
    Protected WithEvents btnGuardar As Global.DevExpress.Web.ASPxButton
    Protected WithEvents btnCancelar As Global.DevExpress.Web.ASPxButton
End Class
