'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class Proveedores

    Protected WithEvents btnNuevo As Global.DevExpress.Web.ASPxButton
    Protected WithEvents btnRefrescar As Global.DevExpress.Web.ASPxButton
    Protected WithEvents btnExportarExcel As Global.DevExpress.Web.ASPxButton
    Protected WithEvents txtBuscar As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents cboFiltroActivo As Global.DevExpress.Web.ASPxComboBox
    Protected WithEvents gridProveedores As Global.DevExpress.Web.ASPxGridView
    Protected WithEvents popupProveedor As Global.DevExpress.Web.ASPxPopupControl
    Protected WithEvents hfProveedorId As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents tabProveedor As Global.DevExpress.Web.ASPxPageControl
    Protected WithEvents txtRazonSocial As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtNombreComercial As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtRFC As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtTelefono As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtEmail As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtSitioWeb As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtCalle As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtNumeroExterior As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtNumeroInterior As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtColonia As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtCodigoPostal As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtCiudad As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtEstado As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtPais As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtNombreContacto As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtCargoContacto As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtTelefonoContacto As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtEmailContacto As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents chkActivo As Global.DevExpress.Web.ASPxCheckBox
    Protected WithEvents btnGuardar As Global.DevExpress.Web.ASPxButton
    Protected WithEvents btnCancelar As Global.DevExpress.Web.ASPxButton

End Class
