'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class ResidentesTelegram

    ' Tabs
    Protected WithEvents tabsResidentes As Global.DevExpress.Web.ASPxPageControl

    ' Grid Residentes
    Protected WithEvents gridResidentes As Global.DevExpress.Web.ASPxGridView

    ' Grid Blacklist
    Protected WithEvents gridBlacklist As Global.DevExpress.Web.ASPxGridView

    ' Popup Residente
    Protected WithEvents popupResidente As Global.DevExpress.Web.ASPxPopupControl
    Protected WithEvents formResidente As Global.DevExpress.Web.ASPxFormLayout
    Protected WithEvents txtChatId As Global.DevExpress.Web.ASPxSpinEdit
    Protected WithEvents txtUsername As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtFirstName As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtLastName As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents cmbEstadoResidente As Global.DevExpress.Web.ASPxComboBox
    Protected WithEvents cmbTipoResidente As Global.DevExpress.Web.ASPxComboBox
    Protected WithEvents txtCreditos As Global.DevExpress.Web.ASPxSpinEdit
    Protected WithEvents txtLimiteTickets As Global.DevExpress.Web.ASPxSpinEdit
    Protected WithEvents chkActivo As Global.DevExpress.Web.ASPxCheckBox
    Protected WithEvents btnGuardarResidente As Global.DevExpress.Web.ASPxButton
    Protected WithEvents btnCancelarResidente As Global.DevExpress.Web.ASPxButton

    ' Popup Blacklist
    Protected WithEvents popupBlacklist As Global.DevExpress.Web.ASPxPopupControl
    Protected WithEvents formBlacklist As Global.DevExpress.Web.ASPxFormLayout
    Protected WithEvents txtRazonBloqueo As Global.DevExpress.Web.ASPxMemo
    Protected WithEvents chkPermanente As Global.DevExpress.Web.ASPxCheckBox
    Protected WithEvents dteFechaLevantamiento As Global.DevExpress.Web.ASPxDateEdit
    Protected WithEvents txtNotasBlacklist As Global.DevExpress.Web.ASPxMemo
    Protected WithEvents btnConfirmarBlacklist As Global.DevExpress.Web.ASPxButton
    Protected WithEvents btnCancelarBlacklist As Global.DevExpress.Web.ASPxButton

    ' Hidden Fields
    Protected WithEvents hfResidenteId As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents hfChatIdBlacklist As Global.System.Web.UI.WebControls.HiddenField

End Class
