'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class Roles
    
    ''' <summary>
    ''' Control txtBuscar.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents txtBuscar As Global.DevExpress.Web.ASPxTextBox
    
    ''' <summary>
    ''' Control cboFiltroActivo.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents cboFiltroActivo As Global.DevExpress.Web.ASPxComboBox
    
    ''' <summary>
    ''' Control btnNuevo.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents btnNuevo As Global.DevExpress.Web.ASPxButton
    
    ''' <summary>
    ''' Control btnRefrescar.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents btnRefrescar As Global.DevExpress.Web.ASPxButton
    
    ''' <summary>
    ''' Control btnExportarExcel.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents btnExportarExcel As Global.DevExpress.Web.ASPxButton
    
    ''' <summary>
    ''' Control gridRoles.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents gridRoles As Global.DevExpress.Web.ASPxGridView
    
    ''' <summary>
    ''' Control popupRol.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents popupRol As Global.DevExpress.Web.ASPxPopupControl
    
    ''' <summary>
    ''' Control hfRolId.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents hfRolId As Global.System.Web.UI.WebControls.HiddenField
    
    ''' <summary>
    ''' Control txtNombre.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents txtNombre As Global.DevExpress.Web.ASPxTextBox
    
    ''' <summary>
    ''' Control txtDescripcion.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents txtDescripcion As Global.DevExpress.Web.ASPxMemo
    
    ''' <summary>
    ''' Control chkActivo.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents chkActivo As Global.DevExpress.Web.ASPxCheckBox
    
    ''' <summary>
    ''' Control btnGuardar.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents btnGuardar As Global.DevExpress.Web.ASPxButton
    
    ''' <summary>
    ''' Control btnCancelar.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents btnCancelar As Global.DevExpress.Web.ASPxButton
    
    ''' <summary>
    ''' Control popupPermisos.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents popupPermisos As Global.DevExpress.Web.ASPxPopupControl
    
    ''' <summary>
    ''' Control hfRolIdPermisos.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents hfRolIdPermisos As Global.System.Web.UI.WebControls.HiddenField
    
    ''' <summary>
    ''' Control rptModulos.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents rptModulos As Global.System.Web.UI.WebControls.Repeater
    
    ''' <summary>
    ''' Control btnGuardarPermisos.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents btnGuardarPermisos As Global.DevExpress.Web.ASPxButton
    
    ''' <summary>
    ''' Control btnCancelarPermisos.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents btnCancelarPermisos As Global.DevExpress.Web.ASPxButton
End Class
