'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class TiposSensor
    Protected WithEvents btnNuevo As Global.DevExpress.Web.ASPxButton
    Protected WithEvents btnRefrescar As Global.DevExpress.Web.ASPxButton
    Protected WithEvents btnExportarExcel As Global.DevExpress.Web.ASPxButton
    Protected WithEvents txtBuscar As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents cboFiltroActivo As Global.DevExpress.Web.ASPxComboBox
    Protected WithEvents gridTipos As Global.DevExpress.Web.ASPxGridView
    Protected WithEvents popupTipo As Global.DevExpress.Web.ASPxPopupControl
    Protected WithEvents hfId As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents txtNombre As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtDescripcion As Global.DevExpress.Web.ASPxMemo
    Protected WithEvents txtUnidadMedida As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtSimboloUnidad As Global.DevExpress.Web.ASPxTextBox
    Protected WithEvents txtUmbralMinimo As Global.DevExpress.Web.ASPxSpinEdit
    Protected WithEvents txtUmbralMaximo As Global.DevExpress.Web.ASPxSpinEdit
    Protected WithEvents chkActivo As Global.DevExpress.Web.ASPxCheckBox
    Protected WithEvents btnGuardar As Global.DevExpress.Web.ASPxButton
    Protected WithEvents btnCancelar As Global.DevExpress.Web.ASPxButton
End Class
