'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class FormulariosDinamicos

    Protected WithEvents gridFormularios As Global.DevExpress.Web.ASPxGridView
    Protected WithEvents gridExporter As Global.DevExpress.Web.ASPxGridViewExporter

End Class