'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class FormularioVistaPrevia

    Protected WithEvents hfFormularioId As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents hfCamposJSON As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents hfPlataformas As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents btnVolver As Global.DevExpress.Web.ASPxButton
    Protected WithEvents lblNombreFormulario As Global.System.Web.UI.WebControls.Label
    Protected WithEvents btnEditar As Global.DevExpress.Web.ASPxButton
    Protected WithEvents lblUrlWeb As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTituloMovil As Global.System.Web.UI.WebControls.Label

End Class
